[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:backend]
command=python3 /app/backend/app.py
directory=/app/backend
autostart=true
autorestart=true
